### PR TITLE
DNM - Testing downgrade libvirt

### PR DESCRIPTION
**Pull request by arxcruz**
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/558

### CODE REVIEW

**Comment by arxcruz** [comment]
recheck

**Comment by arxcruz** [comment]
recheck

**Comment by cescgina** [comment]
recheck

**Comment by arxcruz** [comment]
recheck

**Comment by arxcruz** [comment]
recheck

**Comment by arxcruz** [comment]
recheck

**Comment by raukadah** [comment]
@arxcruz Hello, Do we still need this pr, if not can we close it?

**Pull request closed without merging**
