### PR TITLE
Use test operator to validate changes in both tempest and tobiko images

### PR DESCRIPTION
**Pull request by eduolivares**

### CODE REVIEW

**Comment by kopecmartin** [comment]
lgtm, I support any transition to test-operator

**Comment by eduolivares** [comment]
@lpiwowar @kopecmartin 
thanks for your comments.

I'm fixing the tobiko failed tests.

I have added a commit to this PR adding the podman package to the tobiko image.
And the following 3 tobiko patches need to be approved:
https://review.opendev.org/q/topic:%22fix-sanity-tests-on-podified%22

So the jobs are going to fail again and I will recheck this PR when those tobiko patches are merged.

**Comment by eduolivares** [comment]
recheck
tobiko patches merged

**Review by lpiwowar — APPROVED** [review]
LGTM! Thank you! Both tobiko and tempest tests passed. It seems to be working fine:)

**Review by kopecmartin — APPROVED** [review]
lgtm

**Pull request merged**
