### PR TITLE
[18.0.0-proposed][Tempest] Modify IMAGES_TIMEOUT for individual images

### PR DESCRIPTION
**Pull request by lpiwowar**
This patch allows to modify IMAGES_CREATION_TIMEOUT for individual images. This better fits the interface of the extraImges parameter in the Tempest CR [1].

[1] https://github.com/openstack-k8s-operators/test-operator/pull/166

### CODE REVIEW

**Comment by lpiwowar** [comment]
recheck

**Review by kopecmartin — APPROVED** [review]

**Comment by lpiwowar** [comment]
recheck

**Comment by kopecmartin** [comment]
if the jobs here are broken, can't we just merge it without waiting for those? I can hit merge button right away.

**Comment by kopecmartin** [comment]
recheck

**Comment by kopecmartin** [comment]
recheck

**Comment by lpiwowar** [comment]
@raukadah, can we get a review, please?

**Review by kopecmartin — APPROVED** [review]

**Pull request merged**
