### PR TITLE
Remove collectd

### PR DESCRIPTION
**Pull request by vyzigold**
Remove deprecated collectd container from TCIB

### CODE REVIEW

**Comment by mrunge** [comment]
may need to remove https://github.com/openstack-k8s-operators/tcib/blob/main/container-images/containers.yaml#L17 too

**Comment by mrunge** [comment]
and removing https://github.com/openstack-k8s-operators/tcib/blob/main/container-images/kolla/base/uid_gid_manage.sh#L41 makes sense too

**Comment by vyzigold** [comment]
I messed up the history a little while squashing the commits. I'll fix that

**Comment by raukadah** [comment]
@mrunge Do we want to include this patch for antelope / OSP-18 release?

**Comment by mrunge** [comment]
> @mrunge Do we want to include this patch for antelope / OSP-18 release?

Yes, that needs to get back to Antelope

**Review by raukadah — APPROVED** [review]

**Pull request merged**
