### PR TITLE
Move tcib jobs to update_containers role

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1885
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1884

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
Here is the testresult.
https://logserver.rdoproject.org/78/178/5ef2ceff3bc9c31a5eeceb4fb55cf36c66da05a7/github-check/tcib-podified-multinode-edpm-deployment-crc/5805c4b/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/openstackversions.core.openstack.org/openstack-galera-network-isolation.yaml
Below are the custom containers added via update_containers role
```
spec:
  customContainerImages:
    aodhAPIImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-aodh-api:e72f31c85d92e63dff1ddc22b6d29110
    aodhEvaluatorImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-aodh-evaluator:e72f31c85d92e63dff1ddc22b6d29110
    aodhListenerImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-aodh-listener:e72f31c85d92e63dff1ddc22b6d29110
    aodhNotifierImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-aodh-notifier:e72f31c85d92e63dff1ddc22b6d29110
    barbicanAPIImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-barbican-api:e72f31c85d92e63dff1ddc22b6d29110
    barbicanKeystoneListenerImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-barbican-keystone-listener:e72f31c85d92e63dff1ddc22b6d29110
    barbicanWorkerImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-barbican-worker:e72f31c85d92e63dff1ddc22b6d29110
    ceilometerCentralImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-ceilometer-central:e72f31c85d92e63dff1ddc22b6d29110
    ceilometerComputeImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-ceilometer-compute:e72f31c85d92e63dff1ddc22b6d29110
    ceilometerIpmiImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-ceilometer-ipmi:e72f31c85d92e63dff1ddc22b6d29110
    ceilometerNotificationImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-ceilometer-notification:e72f31c85d92e63dff1ddc22b6d29110
    cinderAPIImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-cinder-api:e72f31c85d92e63dff1ddc22b6d29110
    cinderBackupImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-cinder-backup:e72f31c85d92e63dff1ddc22b6d29110
    cinderSchedulerImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-cinder-scheduler:e72f31c85d92e63dff1ddc22b6d29110
    edpmFrrImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-frr:e72f31c85d92e63dff1ddc22b6d29110
    edpmIscsidImage: 38.102.83.226:5001/podified-antelope-centos9/openstack-iscsid:e72f31c85d92e63dff1ddc22b6d29110
```
and
Here image is used:https://logserver.rdoproject.org/78/178/5ef2ceff3bc9c31a5eeceb4fb55cf36c66da05a7/github-check/tcib-podified-multinode-edpm-deployment-crc/5805c4b/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/barbican-worker-worker-7d55fd98dd-9gljg-describe
```
Containers:
  barbican-worker-log:
    Container ID:  cri-o://9f36bb1f08898c27d103fd1630011ff5d503003c8545098179cdabfa43ed57b4
    Image:         38.102.83.226:5001/podified-antelope-centos9/openstack-barbican-worker:e72f31c85d92e63dff1ddc22b6d29110
    Image ID:      38.102.83.226:5001/podified-antelope-centos9/openstack-barbican-worker@sha256:581fd8db2ab3f9b9e3a04b00d966fa906cc9e32611a4b153b96ff8acc0c82c02
```

**Review by marios — APPROVED** [review]
looks right, dependencies merged 
test result from Chandan at https://github.com/openstack-k8s-operators/tcib/pull/178#issuecomment-2181915631

**Pull request merged**
